name: Quality checks

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  task-checker:
    name: PR check list
    runs-on: ubuntu-latest

    steps:
      - uses: EkoCommunications/PRChecks/task-list@develop
