name: Dev release teardown

on:
  pull_request:
    types: [closed]

jobs:
  env_teardown:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ui-kit-open-source.dev.amity.co
          PATH_TO_DELETE: ${{ github.event.pull_request.number }}

      - uses: strumwolf/delete-deployment-environment@v2
        with:
          environment: dev/${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
