name: Testing

on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2

      - name: cache deps
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            **/node_modules
            **/.eslintcache
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: install deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: eslint checks
        run: npm run lint
